import { AbsoluteFill, Sequence, useCurrentFrame, spring, interpolate, useVideoConfig, Easing, Audio, IFrame } from "remotion";
import React from "react";

// --- Cinematic Background ---
const CinematicBackground: React.FC = () => {
  const frame = useCurrentFrame();
  const scale = interpolate(frame, [0, 2000], [1, 1.1]);
  return (
    <AbsoluteFill style={{
      backgroundColor: "#000",
      backgroundImage: `radial-gradient(circle at center, #0a1128 0%, #000 100%)`,
      transform: `scale(${scale})`
    }}>
      <div style={{
        position: "absolute", width: "100%", height: "100%",
        backgroundImage: `linear-gradient(rgba(0,255,157,0.05) 2px, transparent 2px), linear-gradient(90deg, rgba(0,255,157,0.05) 2px, transparent 2px)`,
        backgroundSize: "60px 60px",
        transform: "perspective(1000px) rotateX(75deg) scale(2.5)",
        transformOrigin: "bottom",
        opacity: 0.8
      }} />
    </AbsoluteFill>
  );
};

// --- Scene 1: The Problem ---
const ProblemScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const opacity = interpolate(frame, [0, 20, 150, 180], [0, 1, 1, 0]);
  const scale = spring({ fps, frame, config: { damping: 14 } });

  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity }}>
      <h1 style={{ fontSize: 90, color: "#fff", transform: `scale(${scale})`, margin: 0 }}>
        How do you trust an <span style={{ color: "#ff3333" }}>AI Agent?</span>
      </h1>
      <h2 style={{ fontSize: 40, color: "#a0aec0", marginTop: 20 }}>
        Manifest spoofing. Private key harvesting. Bait-and-Switch pricing.
      </h2>
    </AbsoluteFill>
  );
};

// --- Scene 2: The Solution ---
const SolutionScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const titleY = interpolate(spring({ fps, frame, config: { damping: 12 } }), [0, 1], [100, 0]);
  const opacity = interpolate(frame, [0, 20, 150, 180], [0, 1, 1, 0]);

  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity }}>
      <h3 style={{ fontSize: 35, color: "#00ff9d", letterSpacing: 8, margin: 0 }}>INTRODUCING</h3>
      <h1 style={{ fontSize: 140, fontWeight: 900, color: "#fff", textShadow: "0 0 50px #00ff9d", margin: 0, transform: `translateY(${titleY}px)` }}>
        PRE-FLIGHT
      </h1>
      <h2 style={{ fontSize: 45, color: "#fff", marginTop: 30 }}>
        The A2MCP Trust & Safety Scanner
      </h2>
    </AbsoluteFill>
  );
};

// --- Scene 3: How it Works (Terminal/API) ---
const CodeDemoScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const opacity = interpolate(frame, [0, 20, 380, 420], [0, 1, 1, 0]);
  const rotateY = interpolate(frame, [0, 400], [20, -10]);

  const code = `// 1. Any User or Agent requests a scan via A2MCP
const res = await fetch("https://okx-genesis-pre-flight.vercel.app/scan", {
  method: "POST",
  body: JSON.stringify({ target_id: "agent-x" })
});

// 2. x402 Protocol Intercepts!
if (res.status === 402) {
  console.log("Pay-per-scan required (0.05 USDT)");
  await executePaymentOnXLayerMainnet();
}

// 3. Pre-Flight executes Live Mystery Shopper On-Chain
// -> Detects Bait-and-Switch pricing traps
// -> Analyzes permissions & malicious payloads

// 4. Report is Cryptographically Signed (EIP-712)
const { signature, html_report_url } = await res.json();`;

  const visibleLength = Math.floor(interpolate(frame, [30, 300], [0, code.length], { extrapolateRight: "clamp", easing: Easing.linear }));

  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity }}>
      <h1 style={{ fontSize: 60, color: "#00ff9d", marginBottom: 30 }}>How it works (x402 Integration)</h1>
      <div style={{ 
        transform: `perspective(1000px) rotateY(${rotateY}deg)`,
        backgroundColor: "#050a14", border: "2px solid #00ff9d", borderRadius: 16, 
        padding: 40, width: "70%", boxShadow: "0 30px 100px rgba(0, 255, 157, 0.2)"
      }}>
        <pre style={{ color: "#fff", fontSize: 28, fontFamily: "monospace", whiteSpace: "pre-wrap", lineHeight: 1.6 }}>
          {code.substring(0, visibleLength)}
          {frame % 15 < 7 ? "█" : ""}
        </pre>
      </div>
    </AbsoluteFill>
  );
};

// --- Scene 4: The Actual Live Report (IFrame) ---
const LiveReportScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const opacity = interpolate(frame, [0, 30, 370, 400], [0, 1, 1, 0]);
  const scale = spring({ fps, frame, config: { damping: 15 } });

  // Use the actual live report URL generated by the Vercel app!
  const reportUrl = "https://okx-genesis-pre-flight.vercel.app/reports/8f18b739-cefd-4b44-a3b4-3609a966b58f";

  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", opacity }}>
      <h1 style={{ fontSize: 60, color: "#00ff9d", textShadow: "0 0 20px #00ff9d", marginBottom: 20 }}>
        The Output: A Cryptographically Signed Report
      </h1>
      <div style={{ 
        transform: `scale(${scale})`,
        width: "80%", height: "70%", 
        borderRadius: 20, overflow: "hidden", 
        border: "4px solid #00ff9d",
        boxShadow: "0 20px 80px rgba(0, 255, 157, 0.4)"
      }}>
        <IFrame 
          src={reportUrl} 
          style={{ width: "100%", height: "100%", border: "none", backgroundColor: "#fff" }} 
        />
      </div>
    </AbsoluteFill>
  );
};

// --- Scene 5: Outro ---
const FinaleScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const enter = spring({ fps, frame, config: { damping: 15 } });
  
  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center" }}>
      <h2 style={{ fontSize: 50, color: "#a0aec0", transform: `translateY(${interpolate(enter, [0,1], [-50, 0])}px)`, opacity: enter }}>
        OKX.AI Genesis Hackathon
      </h2>
      <h1 style={{ fontSize: 130, fontWeight: 900, color: "#fff", transform: `scale(${enter})`, textShadow: "0 0 50px #00ff9d", margin: "10px 0" }}>
        Revenue Rocket Track
      </h1>
      <h2 style={{ fontSize: 50, color: "#00ff9d", marginTop: 20, opacity: enter }}>
        Monetized via x402
      </h2>
    </AbsoluteFill>
  );
};

export const MainVideo: React.FC = () => {
  const audioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3";

  return (
    <AbsoluteFill style={{ backgroundColor: "#000", fontFamily: "sans-serif" }}>
      <Audio src={audioUrl} startFrom={1200} volume={0.8} />
      <CinematicBackground />
      
      {/* 0 - 6s */}
      <Sequence from={0} durationInFrames={180}>
        <ProblemScene />
      </Sequence>

      {/* 6 - 12s */}
      <Sequence from={180} durationInFrames={180}>
        <SolutionScene />
      </Sequence>

      {/* 12 - 26s (Show the API & x402 integration Code) */}
      <Sequence from={360} durationInFrames={420}>
        <CodeDemoScene />
      </Sequence>

      {/* 26 - 40s (Show the ACTUAL HTML Live Report using IFrame) */}
      <Sequence from={780} durationInFrames={400}>
        <LiveReportScene />
      </Sequence>

      {/* 40 - 50s (Finale) */}
      <Sequence from={1180} durationInFrames={320}>
        <FinaleScene />
      </Sequence>
    </AbsoluteFill>
  );
};
